from src.graph.state import MealPlanState
from src.llm.client import get_llm
from src.llm.prompts import MEAL_PLAN_GENERATION_PROMPT
from src.schemas.meal_plan import DailyMealPlan
from src.validation.schema import validate_schema
from src.validation.math import validate_daily_totals
from src.validation.safety import validate_safety
from src.utils.time_slots import generate_meal_times
from src.validation.targets import validate_targets
import json

MAX_RETRIES = 5

def generate_plan(state: MealPlanState) -> MealPlanState:
    if state["retry_count"] >= MAX_RETRIES:
        return state

    if state["retry_count"] == 0:
        print("Generating plan...")
    else:
        print("Regenerating plan...")

    llm = get_llm()

    dietary = state["patient_profile"].get("patient_infos", {}).get("dietary_history", {})
    wake = dietary.get("wake_up_time_24h", "08:00")
    sleep = dietary.get("bedtime_24h", "23:00")

    meal_times = generate_meal_times(wake, sleep)

    prompt = MEAL_PLAN_GENERATION_PROMPT.format(
        patient_profile=state["patient_profile"],
        food_lists=state["available_food_lists"],
        errors=state["validation_errors"],
        schema=DailyMealPlan.model_json_schema(),
        meal_times=meal_times,
    )

    response = llm.invoke(prompt)

    try:
        plan = json.loads(response.content)
        plan["daily_totals"] = calculate_daily_totals(plan["meals"])
        state["current_plan"] = plan
        state["validation_errors"] = []
    except json.JSONDecodeError:
        state["current_plan"] = None
        state["validation_errors"] = ["Invalid JSON generated by LLM."]

    state["retry_count"] += 1
    return state

def validate_plan(state: MealPlanState) -> MealPlanState:
    errors = []

    if not state["current_plan"]:
        errors.append("No plan generated.")
    else:
        errors.extend(validate_schema(state["current_plan"]))
        errors.extend(validate_daily_totals(state["current_plan"]))
        errors.extend(
            validate_targets(
                state["current_plan"],
                state["patient_profile"]
            )
        )

    if errors:
        print("Validation failed:")
        for err in errors:
            print(f" - {err}")
    else:
        print("Validation passed.")

    state["validation_errors"] = errors
    return state

def safety_check(state: MealPlanState) -> MealPlanState:
    if state["current_plan"]:
        errors = validate_safety(
            state["current_plan"], state["patient_profile"]
        )

        if errors:
            print("Safety check failed:")
            for err in errors:
                print(f" - {err}")
        else:
            print("Safety check passed.")

        state["validation_errors"].extend(errors)

    if not state["validation_errors"]:
        print("Success")

    return state

def calculate_daily_totals(meals):
    totals = {
        "kcal": 0,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "fiber_g": 0,
    }

    for meal in meals:
        for key in totals:
            totals[key] += meal["meal_totals"].get(key, 0)

    return {k: round(v, 2) for k, v in totals.items()}